name: Test

on:
  workflow_call:
    secrets:
      aws_access_key:
        required: true
      aws_secret_access_key:
        required: true
      test_email_from:
        required: true
      test_email_recipients:
        required: true

jobs:
  npm-tests:
    name: NPM Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install (ignore scripts)
      run: npm ci --ignore-scripts
    - name: Build
      run: npm run build
    - name: Run NPM tests
      run: npm run test

  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ap-southeast-2
    - name: Run Go tests
      run: go test -v ./...
      env:
        TEST_EMAIL_FROM: ${{ secrets.test_email_from }}
        TEST_EMAIL_RECIPIENTS: ${{ secrets.test_email_recipients }}
