name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: strongishllama/email-service-cdk/.github/workflows/test.yml@${{ $GITHUB_SHA }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      test-email-from: ${{ secrets.TEST_EMAIL_FROM }}
      test-email-recipients: ${{ secrets.TEST_EMAIL_RECIPIENTS }}
