name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    uses: actions/checkout@v2
    uses: .github/workflows/test.yml
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      test-email-from: ${{ secrets.TEST_EMAIL_FROM }}
      test-email-recipients: ${{ secrets.TEST_EMAIL_RECIPIENTS }}
