name: Test

on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      test-email-from:
        required: true
      test-email-recipients:
        required: true

jobs:
  npm-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install (ignore scripts)
      run: npm ci --ignore-scripts
    - name: Build
      run: npm run build
    - name: Run NPM tests
      run: npm run test

  go-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-region: ap-southeast-2
    - name: Run Go tests
      run: go test -v ./...
      env:
        TEST_EMAIL_FROM: ${{ secrets.test-email-from }}
        TEST_EMAIL_RECIPIENTS: ${{ secrets.test-email-recipients }}
